basePath: /
definitions:
  api.CheckRequest:
    properties:
      province:
        example: Lâm Đồng
        type: string
    type: object
  api.CheckResponse:
    properties:
      error:
        type: string
      province:
        type: string
      results: {}
    type: object
  api.TicketRequest:
    properties:
      date:
        example: 07/09
        type: string
      number:
        example: "123456"
        type: string
      province:
        example: Lâm Đồng
        type: string
    type: object
  api.TicketResponse:
    properties:
      date:
        type: string
      error:
        type: string
      input:
        type: string
      match:
        type: string
      prize:
        type: string
      province:
        type: string
    type: object
info:
  contact: {}
  description: API tra cứu kết quả xổ số kiến thiết Việt Nam.
  title: KetQuaXoSo API
  version: "1.0"
paths:
  /api/check:
    post:
      consumes:
      - application/json
      description: Lấy toàn bộ kết quả xổ số của một tỉnh
      parameters:
      - description: Thông tin tỉnh
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.CheckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CheckResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.CheckResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.CheckResponse'
      security:
      - ApiKeyAuth: []
      summary: Lấy kết quả xổ số
      tags:
      - Lottery
  /api/check-ticket:
    post:
      consumes:
      - application/json
      description: Kiểm tra xem vé số có trúng thưởng hay không
      parameters:
      - description: Thông tin vé số
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.TicketRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TicketResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.TicketResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.TicketResponse'
      security:
      - ApiKeyAuth: []
      summary: Kiểm tra vé số
      tags:
      - Lottery
  /api/province:
    get:
      description: Trả về danh sách các tỉnh có hỗ trợ xổ số
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Lấy danh sách tỉnh
      tags:
      - Province
securityDefinitions:
  ApiKeyAuth:
    description: 'Nhập API key để sử dụng API. Giá trị mặc định cho test: **YouAPIKey**'
    in: header
    name: X-API-Key
    type: apiKey
swagger: "2.0"
