name: Build & Release Fyne App

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, android, ios]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build for ${{ matrix.os }}
        env:
          GOOS: ${{ matrix.os }}
        run: |
          echo "Building for $GOOS"
          if [ "$GOOS" = "windows" ]; then
              CC=x86_64-w64-mingw32-gcc fyne package \
                  --os windows \
                  --exe=$(pwd)/KetQuaXoSo.exe \
                  --src=$(pwd)/cmd/gui \
                  --icon $(pwd)/assets/Icon.png \
                  --name="KetQuaXoSo" \
                  --id=com.dopaemon.ketquaxoso \
                  --release
          elif [ "$GOOS" = "linux" ]; then
              fyne package \
                  --os linux \
                  --src=$(pwd)/cmd/gui \
                  --icon $(pwd)/assets/Icon.png \
                  --name="KetQuaXoSo" \
                  --id=com.dopaemon.ketquaxoso \
                  --release
          elif [ "$GOOS" = "android" ]; then
              fyne package \
                  --os android \
                  --name="KetQuaXoSo" \
                  --id=com.dopaemon.ketquaxoso \
                  --icon $(pwd)/assets/Icon.png \
                  --release
          elif [ "$GOOS" = "ios" ]; then
              fyne package \
                  --os ios \
                  --name="KetQuaXoSo" \
                  --id=com.dopaemon.ketquaxoso \
                  --release
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KetQuaXoSo-${{ matrix.os }}
          path: |
            KetQuaXoSo
            KetQuaXoSo.*
